### ISSUE TITLE
Make 0Auth  work in deployed site.

### ISSUE THREAD

**Issue by DianaSuvorova** [DianaSuvorova/ufo-explorer#35]
https://ufo-explorer.netlify.app/api/auth/login

`
{"errorType":"TypeError","errorMessage":"\"secret\" is required","trace":["TypeError: \"secret\" is required","    at Object.get (/var/task/nextPage/chunks/117.js:484:15)","    at Object.getConfig (/var/task/nextPage/chunks/117.js:1096:38)","    at Object.initAuth0 (/var/task/nextPage/chunks/117.js:1742:23)","    at getInstance (/var/task/nextPage/chunks/117.js:1738:24)","    at handleAuth (/var/task/nextPage/chunks/117.js:1844:18)","    at Module.84503 (/var/task/nextPage/pages/api/auth/[...auth0].js:29:127)","    at __webpack_require__ (/var/task/nextPage/pages/api/auth/[...auth0].js:260:43)","    at Module.33938 (/var/task/nextPage/pages/api/auth/[...auth0].js:65:23)","    at __webpack_require__ (/var/task/nextPage/pages/api/auth/[...auth0].js:260:43)","    at /var/task/nextPage/pages/api/auth/[...auth0].js:277:110"]}
`

**Comment by DianaSuvorova** [comment]
not using Auth0
